tap "homebrew/cask"

brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "curl"
brew "findutils"
brew "git"
brew "gnu-sed"
brew "htop-osx"
brew "hub"
brew "icu4c"
brew "jq"
brew "libxml2"
brew "libxslt"
brew "macvim", link: true
brew "nginx"
brew "nodenv"
brew "nvim"
brew "openssl"
brew "python3"
brew "rbenv"
brew "readline"
brew "ruby-build"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn", args: ["ignore-dependencies"]

cask "docker"
cask "visual-studio-code"
