CFG_PATH="${HOME}/dotfiles/shell"

# System- and app-defined paths
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

# bash-completion@2
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

source ${CFG_PATH}/env.sh
source ${CFG_PATH}/secrets.sh
source ${CFG_PATH}/aliases.sh
source ${CFG_PATH}/reverb.sh

bind 'set completion-ignore-case on'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

