CFG_PATH="${HOME}/dotfiles/shell"

# System- and app-defined paths
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

# bash-completion@2
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

source ${CFG_PATH}/env.sh
source ${CFG_PATH}/secrets.sh
source ${CFG_PATH}/aliases.sh
source ${CFG_PATH}/reverb.sh

bind 'set completion-ignore-case on'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/matt/opt/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/matt/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/matt/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/matt/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

